---
title: "Analysis of /a/ production across Stress"
author: "Annie Helms (annie_helms@berkeley.edu)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, dev = "cairo_pdf")
```

Library packages

```{r message = FALSE, warning = FALSE}
library(r2glmm)
library(dplyr)
library(ggplot2)
library(lmerTest) #mixed effects linear regression
library(ggsignif) # helps plot significant relations in ggplot2
library(kableExtra) # formats dataframes in html output
library(BSDA) # manual t-test with means and sd info
library(emmeans) # tukey post-hoc tests
```

### Upload data set

```{r message = FALSE, echo = FALSE}
setwd("/Users/Annie/Box Sync/PhD/github/Bay_Area_Spanish/")
```

Upload productions of /a/ across stress, corpus, and gender.

```{r}
stress_plot = read.csv("plot_model/a_stress_plot.csv", 
                  stringsAsFactors = TRUE)
head(stress_plot, 5) %>%
  kable() %>% # piped to allow for kable formatting
  kable_styling(bootstrap_options = c("striped", # alternates row color in table
                                      "hover", # rows are highlighted when hovered over
                                      "condensed", # row height is condensed
                                      "responsive")) %>% # horizontal scrolling across table
  scroll_box(width = "100%")
```

For plotting purposes, upload vowel plot.

```{r}
area_plot = read.csv("plot_model/area_plot.csv", 
                  stringsAsFactors = TRUE)
head(area_plot, 5) %>%
  kable() %>% # piped to allow for kable formatting
  kable_styling(bootstrap_options = c("striped", # alternates row color in table
                                      "hover", # rows are highlighted when hovered over
                                      "condensed", # row height is condensed
                                      "responsive")) %>% # horizontal scrolling across table
  scroll_box(width = "100%")
```

```{r message = FALSE, echo = FALSE, warning = FALSE}
stress = ggplot(area_plot,
                   aes(x = F2.50_norm,
                       y = F1.50_norm,
                       color = Vowel,
                       shape = Corpus:Gender)) +
  geom_point(size = 2) +
  geom_point(data = stress_plot,
             aes(x = F2.50_norm,
                 y = F1.50_norm,
                 alpha = stress)) +
  theme_classic() +
  #xlim(c(2800, 500)) + # reverses axis scale
  #ylim(c(900, 300)) + # reverses axis scale
  labs(x = "Normalized F2",
       y = "Normalized F1",
       title = "Spanish vowel space: /a/ across stress") +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        axis.title = element_text(size = 12),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.position = "right")
stress
```


